config/routes.rb
MyCircle::Application.routes.draw do
  
  resources :categories

  get 'vendors/searchbylocation'
  get 'vendors/vendorscategory'
  
  resources :vendors
  
               

end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Paperclip
  
  
  field :cat, :type => String
  
  
  has_mongoid_attached_file :catbanner
  do_not_validate_attachment_file_type :catbanner
  
  belongs_to :vendor
end

app/models/vendor.rb
class Vendor
  include Mongoid::Document
  include Mongoid::Paperclip

  field :name, :type => String
  field :address, :type => String
  field :long, :type => String
  field :lati, :type => String

  has_mongoid_attached_file :banner
  do_not_validate_attachment_file_type :banner
  
  has_many :categories, autosave: true
  accepts_nested_attributes_for :categories, :allow_destroy => true, :reject_if => lambda{ |a| a.any? {|k,v| v.blank?} } 

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors}
       #render :json => @vendor.to_json(:methods => [:banner_url])
    end
  end	

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new
    1.times{@vendor.categories.build }
    respond_to do |format|  
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  def searchbylocation
    
     rad_per_deg = Math::PI/180  # PI / 180
     rkm = 6371                  # Earth radius in kilometers
     rm = rkm * 1000             # Radius in meters
     loc1 = Array.new
     loc2 = Array.new
    
       @lat = params[:lat]
       @lon = params[:lon]
       @mdist = params[:mdist]
       
      puts "dist"+ @mdist.to_s
      puts "LAT"+ @lat.to_s
      puts "Lon"+ @lon.to_s
      
      @vendorindist = Array.new
      @vendors = Vendor.all
      @vendors.each do |vendor|
        
          loc1[0]= @lat.gsub(/[^\d\.]/, '').to_f
          loc1[1]= @lon.gsub(/[^\d\.]/, '').to_f
          loc2[0]= vendor.lati.gsub(/[^\d\.]/, '').to_f
          loc2[1]= vendor.long.gsub(/[^\d\.]/, '').to_f
          dlat_rad = (loc1[0]-loc2[0]) * rad_per_deg  # Delta, converted to rad
          dlon_rad = (loc1[1]-loc2[1]) * rad_per_deg

          lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
          lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

          a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
          c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))
          dis =  rkm * c # Delta in meters
          puts "++++++++++++++++++++++++" + dis.to_s
          if( dis <= @mdist.gsub(/[^\d\.]/, '').to_f)
            puts "*******************" + dis.to_s
           
            @vendorindist<<vendor
          end
        
      end
        
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @vendorindist}
      end
      
  end
  
  def vendorscategory
    vendorid = params[:vendorid]
    @categories = Category.where(:vendor_id => vendorid)
    
       
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @categories}
      end
  end
  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :cat
    = f.text_field :cat
  .field
    = f.label :catbanner
    = f.file_field :catbanner
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Vendor
    %th Cat
    %th Banner
    %th

  - @categories.each do |category|
    %tr
      %td= Vendor.find(category.vendor_id).name
      %td= category.cat
      %td= image_tag category.catbanner.url
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Cat:
  = @category.cat

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCircle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vendors/_form.html.haml
= nested_form_for @vendor,  :html => { :multipart => true }do |f|
  - if @vendor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vendor.errors.count, "error")} prohibited this vendor from being saved:"
      %ul
        - @vendor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :long
    = f.text_field :long
  .field
    = f.label :lati
    = f.text_field :lati
  .field
    = f.label :Banner
    = f.file_field :banner
    
    = f.fields_for :categories, :categories  do |c|
      .field
        =c.label :Cat
        =c.text_field :cat
        =c.link_to_remove 'remove'
        
    = f.link_to_add 'add', :categories

        

  .actions
    = f.submit 'Save'

app/views/vendors/edit.html.haml
%h1 Editing vendor

= render 'form'

= link_to 'Show', @vendor
\|
= link_to 'Back', vendors_path

app/views/vendors/index.html.haml
%h1 Listing vendors

%table
  %tr
    %th Name
    %th Address
    %th Long
    %th Lati
    %th Banner
    %th
    %th

  - @vendors.each do |vendor|
    %tr
      %td= vendor.name
      %td= vendor.address
      %td= vendor.long
      %td= vendor.lati
      %td= image_tag vendor.banner.url
      %td= link_to 'Show ', vendor
      %td= link_to 'Edit', edit_vendor_path(vendor)
      %td= link_to 'Destroy', vendor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Vendor', new_vendor_path

app/views/vendors/new.html.haml
%h1 New vendor

= render 'form'

= link_to 'Back', vendors_path

app/views/vendors/searchbylocation.html.haml
%h1 Listing vendors

%table
  %tr
    %th Name
    %th Address
    %th Long
    %th Lati
    %th Distance
    %th Banner
    %th
    %th

  - @vendorindist.each do |vendor|
   
    %tr
      %td= vendor.name
      %td= vendor.address
      %td= vendor.long
      %td= vendor.lati
      %td= image_tag vendor.banner.url
      %td= link_to "Show Category ", {:controller => "vendors", :action => "vendorscategory", :vendorid => vendor.id }
      %td= link_to 'Edit', edit_vendor_path(vendor)
      %td= link_to 'Destroy', vendor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Vendor', new_vendor_path

app/views/vendors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @vendor.name
%p
  %b Address:
  = @vendor.address
%p
  %b Long:
  = @vendor.long
%p
  %b Lati:
  = @vendor.lati

= link_to 'Edit', edit_vendor_path(@vendor)
\|
= link_to 'Back', vendors_path

app/views/vendors/vendorscategory.html.haml
%h1 Listing categories

%table
  %tr
    %th Vendor
    %th Cat
    %th Banner
    %th

  - @categories.each do |category|
    %tr
      %td= Vendor.find(category.vendor_id).name
      %td= category.cat
      %td= image_tag category.catbanner.url
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br